# Generated by Django 2.0.4 on 2018-04-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bsnlsitedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=200)),
                ('btstype', models.CharField(max_length=8)),
                ('btsmake', models.CharField(max_length=200)),
                ('battery', models.CharField(max_length=5)),
                ('powerplant', models.CharField(max_length=4)),
                ('ac', models.CharField(max_length=2)),
            ],
        ),
    ]
