# Generated by Django 2.0.4 on 2018-05-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsnlsite', '0003_auto_20180417_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsnlsitedb',
            name='sitename',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
