# Generated by Django 2.0.4 on 2018-05-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsnlsite', '0004_auto_20180501_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsnlsitedb',
            name='ac1make',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bsnlsitedb',
            name='ac2make',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bsnlsitedb',
            name='ac3make',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bsnlsitedb',
            name='ac4make',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bsnlsitedb',
            name='ac5make',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bsnlsitedb',
            name='battery',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bsnlsitedb',
            name='btsmake',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bsnlsitedb',
            name='powerplant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
